-- Admin bootstrap (run manually after first signup — never commit passwords)
--
-- 1. Sign up through the app at /signup
-- 2. Promote that account in Supabase SQL Editor:
--
--    UPDATE public.profiles
--    SET role = 'admin'
--    WHERE email = 'your-email@example.com';
--
-- See docs/ADMIN_SETUP.md for full instructions.
